In [3]:
#Numpy==> Numerical Python ==> open source library==> for scientific calculation

#list ==> Mutable, Computation power easy

#Difference between List and Numpy?

# 1. Memory usage==> List (High) , Numpy(low)

#2. Time Consuming ==> List (High), Numpy(low)

#3.List==> different -different type elements

#Numpy ==> Arra format



In [5]:
!pip install numpy 


[notice] A new release of pip is available: 23.0.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np 

In [8]:
a = [1,2,3]
b = np.array(a)
b

array([1, 2, 3])

# How to create a user define array ?


In [10]:
a=[]
size=int(input("Enter the size"))
for i in range (size):
    val=int(input("enter your item:"))
    a.append(val)

b=np.array(a)
b

Enter the size 3
enter your item: 4
enter your item: 6
enter your item: 8


array([4, 6, 8])

# One Dimensional Array

In [11]:
a=[1,2,3]
b=np.array(a)
b

array([1, 2, 3])

In [13]:
print("Total Dimension :",b.ndim) #ndim==> d dimensional data
print("Total shape:", b.shape) #shape= n(rows), n (column)
print("Total Elements:",b.size) #size=n (rows)*n(column)

Total Dimension : 1
Total shape: (3,)
Total Elements: 3


# 2-D data

In [16]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
print("Total Dimension :",b.ndim) #ndim==> d dimensional data
print("Total shape:", b.shape) #shape= n(rows), n (column)
print("Total Elements:",b.size) #size=n (rows)*n(column)

Total Dimension : 2
Total shape: (3, 3)
Total Elements: 9


# Pre - Defined functions 

In [18]:
#(1).zeros() ==> it will create all values into 0

In [19]:
a=np.zeros(5)

a

array([0., 0., 0., 0., 0.])

In [20]:
#Images ==> Pixels (0-255)==> 0px ==> complete black , 255 ==> complete white
#Normalize ==> min_pixels _value =0 , max=1
#weights initialization

In [21]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
print("Total Dimension :",a.ndim) #ndim==> d dimensional data
print("Total shape:", a.shape) #shape= n(rows), n (column)
print("Total Elements:",a.size) #size=n (rows)*n(column)

Total Dimension : 2
Total shape: (3, 4)
Total Elements: 12


# (2). Ones ()==> It will create an array in which all the elements are one

In [24]:
a=np.ones(4)
a

array([1., 1., 1., 1.])

In [25]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
print("Total Dimension :",a.ndim) #ndim==> d dimensional data
print("Total shape:", a.shape) #shape= n(rows), n (column)
print("Total Elements:",a.size) #size=n (rows)*n(column)

Total Dimension : 2
Total shape: (3, 4)
Total Elements: 12


# (3) EYE() ==> diagonal position elements = 1, rest all 0

In [27]:
a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [28]:
a= np.eye(4,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# (4) diag()==> Diagonal Position ==> custom array, rest all are 0

In [29]:
a=np.array([1,25,78,90])
a

array([ 1, 25, 78, 90])

In [30]:
b=np.diag(a)
b

array([[ 1,  0,  0,  0],
       [ 0, 25,  0,  0],
       [ 0,  0, 78,  0],
       [ 0,  0,  0, 90]])

# (5). Random Module 

In [31]:
#(a). Randint() ==> provide integer number in a given range
#syntax : np.random.randint(min_number, max_number,total_number)


In [32]:
a=np.random.randint(1,20,4)
a

array([14, 12, 11, 19])

In [33]:
p=int(input("Enter min number:"))
q=int(input("Enter max number:"))
r=int(input("Enter total number:"))
a=np.random.randint(p,q,r)
a

Enter min number: 1
Enter max number: 100
Enter total number: 6


array([53, 69, 75, 74, 23, 52])

In [34]:
#(b) Rand()==> Limit(0-1)
a=np.random.rand(5)
a

array([0.26908048, 0.26487009, 0.67518806, 0.98253019, 0.12042856])

In [36]:
a=np.random.rand(2,3)
a

array([[0.89323652, 0.77059509, 0.68100142],
       [0.83916523, 0.42650825, 0.771841  ]])

In [37]:
#(c) Randn() ==> limit(-7 to +7)
a=np.random.randn(8)
a

array([-0.01536061,  1.41950081,  1.38116203, -0.66737971,  0.07516421,
       -0.74897253, -0.0273642 ,  1.16584579])

In [38]:
a=np.random.randn(2,3)
a

array([[-0.3558142 ,  0.50254426, -0.84601012],
       [ 1.05361159, -1.35429277, -1.16182635]])

In [39]:
#(d) Seed ()==> it will fix our numbers

In [44]:
np.random.seed(5899)

a=np.random.randint(1,10,2)
a

array([4, 8])