In [1]:
import numpy as np


# Reshaping the data

In [3]:
#n(rows)*n(columns)=n(total_elements)

#n(rows)=n(total_elements)/n(columns)

#n(columns)=n(total_elements)/n(rows)


In [4]:
a=np.random.randint(1,50,12)
a

array([31, 40, 48, 31, 42,  7, 49, 12, 34, 37, 43, 18])

In [5]:
# 1*12,12*1
# 2*6, 6*2
# 3*4 , 4*3

In [6]:
a.reshape(2,6)

array([[31, 40, 48, 31, 42,  7],
       [49, 12, 34, 37, 43, 18]])

In [7]:
a.reshape(6,2)

array([[31, 40],
       [48, 31],
       [42,  7],
       [49, 12],
       [34, 37],
       [43, 18]])

In [12]:
a.reshape(3,4)

array([[31, 40, 48, 31],
       [42,  7, 49, 12],
       [34, 37, 43, 18]])

In [13]:
a.reshape(4,3)

array([[31, 40, 48],
       [31, 42,  7],
       [49, 12, 34],
       [37, 43, 18]])

In [14]:
a.reshape(1,12)

array([[31, 40, 48, 31, 42,  7, 49, 12, 34, 37, 43, 18]])

In [15]:
a.reshape(12,1)

array([[31],
       [40],
       [48],
       [31],
       [42],
       [ 7],
       [49],
       [12],
       [34],
       [37],
       [43],
       [18]])

In [17]:
#1-100 , 36 numbers

# 1*36 , 36*1
# 2*18 , 18*2
# 3*12 , 12*3
# 4*9  , 9*4

In [19]:
a=np.random.randint(1,100,36)
a

array([60, 39,  1, 90, 45, 51, 25, 34,  2,  1, 84, 76, 59, 32,  7, 41,  2,
       66, 37, 24, 34, 14, 49, 82, 73, 54, 37, 72, 55, 17, 40, 76, 84, 83,
       60, 93])

In [20]:
a.reshape(2,18)

array([[60, 39,  1, 90, 45, 51, 25, 34,  2,  1, 84, 76, 59, 32,  7, 41,
         2, 66],
       [37, 24, 34, 14, 49, 82, 73, 54, 37, 72, 55, 17, 40, 76, 84, 83,
        60, 93]])

In [21]:
a.reshape(18,2)

array([[60, 39],
       [ 1, 90],
       [45, 51],
       [25, 34],
       [ 2,  1],
       [84, 76],
       [59, 32],
       [ 7, 41],
       [ 2, 66],
       [37, 24],
       [34, 14],
       [49, 82],
       [73, 54],
       [37, 72],
       [55, 17],
       [40, 76],
       [84, 83],
       [60, 93]])

In [23]:
a.reshape(3,12)

array([[60, 39,  1, 90, 45, 51, 25, 34,  2,  1, 84, 76],
       [59, 32,  7, 41,  2, 66, 37, 24, 34, 14, 49, 82],
       [73, 54, 37, 72, 55, 17, 40, 76, 84, 83, 60, 93]])

In [24]:
a.reshape(12,3)

array([[60, 39,  1],
       [90, 45, 51],
       [25, 34,  2],
       [ 1, 84, 76],
       [59, 32,  7],
       [41,  2, 66],
       [37, 24, 34],
       [14, 49, 82],
       [73, 54, 37],
       [72, 55, 17],
       [40, 76, 84],
       [83, 60, 93]])

In [25]:
a.reshape(4,9)

array([[60, 39,  1, 90, 45, 51, 25, 34,  2],
       [ 1, 84, 76, 59, 32,  7, 41,  2, 66],
       [37, 24, 34, 14, 49, 82, 73, 54, 37],
       [72, 55, 17, 40, 76, 84, 83, 60, 93]])

In [26]:
a.reshape(9,4)

array([[60, 39,  1, 90],
       [45, 51, 25, 34],
       [ 2,  1, 84, 76],
       [59, 32,  7, 41],
       [ 2, 66, 37, 24],
       [34, 14, 49, 82],
       [73, 54, 37, 72],
       [55, 17, 40, 76],
       [84, 83, 60, 93]])

# View VS Copy

In [28]:
a=np.array([10,20,30,40,50,60,70,80])#view means modification in original data
b=a[3:6]#3,4,5 indexed elements=40,50,60
b[:]=0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [29]:
a=np.array([10,20,30,40,50,60,70,80])#copy means we make a duplicate elements
b=a[3:6].copy()
b[:]=0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

# Conditional Selection

In [30]:
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [32]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [33]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [34]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

# Operations ON Array

In [35]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [36]:
a*2 #array

array([2, 4, 6, 8])

In [37]:
a**2 #square

array([ 1,  4,  9, 16])

In [38]:
a**3  #cube

array([ 1,  8, 27, 64], dtype=int32)

In [39]:
a=a.reshape(2,2)
a   

array([[1, 2],
       [3, 4]])

In [40]:
b= np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [41]:
a+b

array([[ 6,  8],
       [10, 12]])

In [42]:
a-b

array([[-4, -4],
       [-4, -4]])

In [43]:
a.dot(b) #multipilaction of array in matrix

array([[19, 22],
       [43, 50]])

In [44]:
np.min(a)

1

In [46]:
np.argmin(a) #index value 

0

In [47]:
np.max(a)

4

In [48]:
np.argmax(a)

3

In [49]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [50]:
np.sin(a)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [51]:
np.tan(a)

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128]])

In [52]:
np.cos(a)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

# LinSpace() ==  This function returns value between a given range and with a same gape betweeen consicuitve elemets

In [54]:
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [55]:
# 1.25 -1 =0.25
# 1.50 - 1.25 = 0.25
# 1.75 - 1.50 = 0.25
# 2 - 1.75 = 0.25

In [56]:
np.random.seed(122)
a= np.random.randint(1,21,9).reshape(3,3)
a


array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [57]:
np.sum(a)

116

In [58]:
np.sum(a, axis =1) #row wise operation

array([40, 46, 30])

In [59]:
np.sum(a, axis =0) #column wise operation

array([36, 40, 40])

In [60]:
np.cumsum(a)

#cumsum==> a,b,c,d==> a,a+b,a+b+c,a+b+c+d


array([ 16,  27,  40,  57,  70,  86,  89, 105, 116])

# np.unique(arr , return_index =True , return_counts = True)

returns 3 array

1. The array with unique values

2. The array with respective index values 

3. The array with counting of frequency

In [63]:
a=np.array([10,20,30,40,50,20,20,20,20,50,50,20,20,20])
np.unique(a , return_index = True , return_counts = True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 4], dtype=int64),
 array([1, 8, 1, 1, 3], dtype=int64))

# Horizontal  and Vertical Stacking

In [66]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [67]:
b

array([5, 6, 7, 8])

In [68]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [70]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11,12])

In [71]:
b

array([5, 6, 7, 8])

In [72]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [73]:
np.stack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])